from .score_jump_distance import score_jump_distance
from .calc_angle import calc_angle
from .arm_takeoff import arm_takeoff
from .score_arm_takeoff import score_arm_takeoff
from .flight_phase import flight_phase
from .score_flight_phase import score_flight_phase
from .landing_stability import landing_stability
from .score_landing_stability import score_landing_stability
from .composite_technique_score import composite_technique_score
from .predict_category import predict_category
from .add_data import add_data
from .long_jump import long_jump
